Update build-authentik2.yaml
Signed-off-by: Lavish Gupta <146554957+lavishiamops@users.noreply.github.com>

diff --git a/.github/workflows/build-authentik2.yaml b/.github/workflows/build-authentik2.yaml
--- a/.github/workflows/build-authentik2.yaml
+++ b/.github/workflows/build-authentik2.yaml
@@ -34,6 +34,13 @@ jobs:
     name: Build Authentik Image
     runs-on: ubuntu-latest
     steps:
+      - name: Check Branch and Fail if 'supreme'
+        run: |
+          if [[ "${{ github.ref }}" == "refs/heads/supreme" ]]; then
+            echo "Failing the workflow because it's running from the supreme branch."
+            exit 1
+          fi
+          
       - name: Checkout
         uses: actions/checkout@v4
 
